### ISSUE TITLE
Add ID annotator code

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/id-annotator-example#1]
Follow the example and documentation provided by the [Date Annotator example](https://github.com/nlpsandbox/date-annotator-example). Use and adapt this information to create an example tool in Python from the specification of the upcoming ID annotator.

## Tasks

- [ ] Create DockerHub repository for the image generated by the CI workflow of this repo
- [ ] Give this repo permission to push image to DockerHub
- [ ] Add the initial code base
  - Copy/paste files from the Data annotator example. Delete the content of the folder `server/openapi_server`. Adapt the remaining files by replacing references to "date" by "ID".
  - Make sure the file `package.json` has been updated, then run `npm run generate:server:latest` to generate the server code.
- [ ] Open a PR that implements this ticket.

**Comment by tschaffter** [comment]
Created the Docker [repository nlpsandbox/id-annotator-example](https://hub.docker.com/repository/docker/nlpsandbox/id-annotator-example/general)
